### DISCUSSION TITLE
Default envvar value required to run?

### DISCUSSION THREAD

**Discussion by michaelwooley** [neverendingqs/serverless-dotenv-plugin#253] [Q&A]
I'm seeing that I must provide a default value for environment variables in order for my commands to run.

In short:

```yaml
${env:MY_ENV}      # FAILS

${evn:MY_ENV, ''}  # OK
```

# Command results

## Without default environment variable value

If I run without a default value (i.e. `${env:MY_ENV}`) I get:

```bash
❯ serverless package
Running "serverless" from node_modules
Environment: linux, node 16.16.0, framework 3.36.0 (local) 3.36.0v (global), plugin 7.1.0, SDK 4.4.0
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
Cannot resolve serverless.yml: Variables resolution errored with:
  - Cannot resolve variable at "provider.environment.MY_ENV": Value not found at "env" source
```

## **With** default environment variable value

If I add a default value (i.e. `${env:MY_ENV, ''}`) I get:

```bash
❯ serverless package
Running "serverless" from node_modules
DOTENV: Loading environment variables from .env:
         - MY_ENV

Packaging aws-python-http-api-project for stage dev (us-east-1)
```

#  Example `serverless.yaml` file

(Modified version of the boilerplate project. Similar to [serverless/examples/aws-python-http-api](https://github.com/serverless/examples/blob/22865199326008b9f863cb1ad28bfdddae9a7473/aws-python-http-api/serverless.yml).)

```yaml
service: aws-python-http-api-project

provider:
  name: aws
  runtime: python3.9
  environment:
    MY_ENV: ${env:MY_ENV, ''} # Must include default!

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get

plugins:
  - serverless-dotenv-plugin

custom:
  dotenv:
    logging: true
```

# Version info

```bash
❯ sls --version
Running "serverless" from node_modules
Framework Core: 3.36.0 (local) 3.36.0 (global)
Plugin: 7.1.0
SDK: 4.4.0
```
