### ISSUE TITLE
System environment variables (wrongly) take higher precedence than the .env file

### ISSUE THREAD

**Issue by cklll** [neverendingqs/serverless-dotenv-plugin#152]
Please include a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).

**Repro**
I use docker/docker-compose for both development and deployment
I set environment variable in `docker-compose.yml`
```
environment:
  SMTP_PORT: 1025
```
This is for development (`sls offline start`)

Then I also have `.env`  file in the directory and it contains
```
SMTP_PORT=465
```
This is for deploying to production

My `serverless.yml`
```yml
custom:
  dotenv:
    include:
      - SMTP_PORT
    required:
      env:
        - SMTP_PORT
      file: true
```

**Actual**
In Lambda, `SMTP_PORT` is set to 1025

**Expect**
In Lambda, `SMTP_PORT` is set to 465

------

I can easily get around the problem by having a separate container for deployment, I guess.
But my expectation is that the plugin should only load the environment variables from file.

Let me know if you need a full working example. 
But I think this should be fairly straightforward to confirm whether this is a valid bug
