### ISSUE TITLE
Feature request: throw on missing required environment vars

### ISSUE THREAD

**Issue by tommedema** [neverendingqs/serverless-dotenv-plugin#20]
It would be great if the plugin could be configured to throw if a set of required environment vars are missing, either through an `.env` file or any other means of setting environment vars.

**Comment by levino** [comment]
Could someone please explain why this issue has not been reacted upon? I would find this very useful: I mean if your code will not work without a certain environment variable the deployment will be executed "successfully" but the server code will crash or do something stupid so basically you just killed your service... Totally unnecessary because one could easily do a predeployment check that all necessary environment variables are set. Maybe it could be as simple as using [`dotenv-safe`](https://www.npmjs.com/package/dotenv-safe).

**Comment by colynb** [comment]
Hi @Levino I have not been great at responding to these requests because I'm nervous about the possibility of introducing breaking changes. There are thousands of devs who depend on this plugin and are using it ways that I can't always imagine. So I lean on not making any changes at all at the risk of not introducing good ideas like this one. It would be super helpful if you could provide some guidance on how to introduce this feature without any possibility of a breaking change. Thanks!

**Comment by colynb** [comment]
I think something like this could possibly work without introducing a breaking change (instead of using dotenv-safe). Note, the `required` option

```
custom:
  dotenv:
    path: path/to/my/.env (default ./.env)
    basePath: path/to/ (default ./)
    logging: false
    required:
      - AUTH0_CLIENT_ID
      - AUTH0_CLIENT_SECRET
```

What would you like the response to be if the required vars are not there?
