### ISSUE TITLE
Does this support stages?

### ISSUE THREAD

**Issue by dcworldwide** [neverendingqs/serverless-dotenv-plugin#3]
I have env specific var files. I.e. .env.dev, .env.prod. I'd like to use the stage to determine which file to load..

**Comment by schickling** [comment]
I've tried to solve it like this

```yml
custom:
  envfile:
    dev: .env
    prod: .env.prod
  dotenv:
    path: ${self:custom.envfile.${opt:stage, 'dev'}}
```

Unfortunately, this plugin doesn't seem to resolve the var syntax.

**Comment by colynb** [comment]
I'll see what I can do

**Comment by schickling** [comment]
Thanks a lot @colynb! Highly appreciated!

**Comment by colynb** [comment]
this has been resolved with https://github.com/infrontlabs/serverless-dotenv-plugin/pull/6

**Comment by rapkyt** [comment]
Has this been reversed? I can't use `path: .env.${opt:stage}` on version 2.3.2

**Comment by andidev** [comment]
@rapkyt for some reason path does not support variables.
for example this works for me:
```
path: .env.dev
```

but this does not
```
path: .env.${'dev'}
```

**Comment by rapkyt** [comment]
@andidev 
I don't know what happened before that I couldn't get a file per environment, but now I've put all my env files I.e. .env.dev, .env.prod, inside a folder called `config` and this setting did the trick
```yml
config:
  dotenv:
    basePath: config/
```

Also I run all serverless comamnds passing stage and env variables, i.e.:
```bash
serverless deploy --stage {env_name} --env {env_name}
```
