### ISSUE TITLE
How to *NOT* load into Lambda?

### ISSUE THREAD

**Issue by cyberfox1** [neverendingqs/serverless-dotenv-plugin#30]
I further suffix env vars I load from files in serverless.yaml, so I don't want the original vars loaded into Lambda. Is there an option to turn that off?

**Comment by diegoaguilar** [comment]
@cyberfox1 did you find a workaround for this?

**Comment by cyberfox1** [comment]
I think I just went back to using sls's file() operator, e.g.

environment: ${file(env.yml):${self:custom.stage}, file(env.yml):default}

**Comment by colynb** [comment]
@cyberfox1 did you check the `include` option that you can set in your yaml file? It allows you to whitelist which variables you want to get pushed into your lambda. You might be asking for a blacklist but right now, that's not available.

**Comment by daaru00** [comment]
@cyberfox1  I use this workaround to completely swtich off this feature:
```yaml
custom:
  dotenv:
    include:
      - disabled # can be false, 'nope', 'no-one'...
```
this exploit the option `include` (mentioned before by @colynb) to pass an array with only one (non-existing) variable named "disabled" and so **no environment variable** (loaded from `.env` file) **will be set** on deployed Lambdas.

Personally I prefer a configuration approach instead of directly load environment variables from `.env` file:
```yaml
custom:
  myConfig: ${env:ENV_VAR_LOADED_FROM_FILE, 'default value'}
```
and then set up Lambda's environment variable only for those who require it:
```yaml
functions:
  myFuncA:
    handler: functions/a.handler # can access 'myConfig' value from MY_CONFIG env var
    environment:
      MY_CONFIG: ${self:custom.myConfig} 

  myFuncB:
    handler: functions/b.handler # cannot access 'myConfig' value
```
