### ISSUE TITLE
How to set different/separated env vars per function?

### ISSUE THREAD

**Issue by delgermurun** [neverendingqs/serverless-dotenv-plugin#35]
Hello,
Thank you for creating an amazing useful library.

Can I set some vars only for one(or more) functions in a project?

Thanks.

**Comment by redlickigrzegorz** [comment]
It's a very good question. I didn't find any possibility to set this with the usage of this library that's why I decided to create my own `config.js` file to keep all the needed env variables and put them where I want during the work with `serverless` 😃 

@colynb is it possible to do this via your library?

**Comment by colynb** [comment]
Would you mind describing a use-case/scenario so that I can get a better understanding? Thanks

**Comment by redlickigrzegorz** [comment]
@colynb Yes, of course, and I believe that it will be a simple example 😉 
```
functions:
  sample-funtion-a:
    handler: src/handler.sampleFunctionA
    environment:
      SAMPLE_A: ${env:SAMPLE_A}
  sample-funtion-b:
    handler: src/handler.sampleFunctionB
    environment:
      SAMPLE_B: ${env:SAMPLE_B}
```
With the current functionality, we will get `SAMPLE_A` and `SAMPLE_B` in the environment section of both functions.

**Comment by ChristopheBougere** [comment]
I'm having a similar use case: I want to load env variables in my fargate task definition, but not in my lambda functions.
Your snippet should work if you add this setting:
```yaml
custom:
  dotenv:
    include: [] # Do not inject env variables into lambdas
```
Having an option to disable auto injection could be great by the way :)
