### ISSUE TITLE
Reference to env vars sitting outside main config yml causes error

### ISSUE THREAD

**Issue by DavidHe1127** [neverendingqs/serverless-dotenv-plugin#38]
### Error:
```
 Serverless Plugin Error --------------------------------------

  Cannot create property 'DYANMODB_TABLE' on string '${file(./serverless-env.yml):environment}'
```

### configs:
serverless.yml
```yml
service: my-service

plugins:
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs8.10
  environment: ${file(./serverless-env.yml):environment}
```
serverless-env.yml
```
environment:
  SLS_AWS_STAGE: ${env:DYANMODB_TABLE, 'xxvvv'}
```

No errors when moving `environment` to outside the `provider`. Verified that it's working perfectly when it's located outside `provider`.
