### ISSUE TITLE
Unable to get .env with a dynamic path

### ISSUE THREAD

**Issue by ANVESH96** [neverendingqs/serverless-dotenv-plugin#57]
I am trying to set dynamic .env files based on stage. The serverless is unable to find those .env files.

Here is my serverless.yml file:
```
custom:
   dotenv:
      path: environment/.env.${self:provider.stage}
provider:
  stage: ${opt:stage, 'dev'}
```

If the path is static as below, it is working just fine
```
custom:
       dotenv:
           path: environment/.env.dev
```

Expected behavior:
DOTENV should resolve path to environment/.env.dev

Current behavior:
Unable to resolve path
