### ISSUE TITLE
The --stage parameter ignored when looking for the right .env file

### ISSUE THREAD

**Issue by AndreyTomilinXmpi** [neverendingqs/serverless-dotenv-plugin#59]
I'm running the serverless script with the next command line:
client deploy **--stage prod** --region eu-west-1 --aws-profile MyProfile

As you see I'm specifying the **--stage** parameter, which according to [this documentation](https://www.serverless.com/plugins/serverless-dotenv-plugin/) should use the **.env.prod** file.

But I'm getting this message:
_Serverless: DOTENV: Could not find .env file._

All **.env** files are in sub-folder **envs** and here is my serverless config:

```
service: my-sevice-${opt:stage, self:provider.stage}

frameworkVersion: ">=1.1.0 <2.0.0"

plugins:
  - serverless-finch
  - serverless-dotenv-plugin

custom:
  dotenv:
    basePath: ./envs/
    include:
      - MY_VARIABLE

  ...

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'develop'}
```
