### ISSUE TITLE
Question: Interpolation inside of .env* files?

### ISSUE THREAD

**Issue by bastiankoetsier** [neverendingqs/serverless-dotenv-plugin#62]
Hey,

first of all: Thank you for your work on this plugin. We just started implementing a serverless api and need env-var support. Unfortunately, we need access to Cloudformation-Outputs inside of the env vars, e.g. for a Subnet-ID. 
What we did so far is more of a workaround by specifying the env vars multiple times: 
```yaml
custom:
  stage: "${opt:stage,'dev'}",
  env:
    dev:
      dbHost: "127.0.01"
    prod: 
      dbHost: "${cf:Stack.dbHost}"

...
functions:
  test:
  ..
    environment: 
      dbHost: "self:custom.env.${opt.stage}.dbHost
``` 
(no guarantees on correct indentation 😄 )
We would love to manage all of the env variables in their dedicated files and just have a `${env:dbHost}` in the functions section without the ugly repetition in `custom` . Is there a way to achieve this? 

Thanks in advance!
