### ISSUE TITLE
Using serverless-dotenv-plugin increases lambda package size 

### ISSUE THREAD

**Issue by thiagodelgado111** [neverendingqs/serverless-dotenv-plugin#83]
Hey guys, sorry to bother you, I really enjoyed how easy it is to use the plugin. Nevertheless, I'm having issues trying to deploy bc my package's final size is pretty big, over 270MB. That being said, I don't know if it has anything to do with the plugin, but when I remove it, it goes down to 405KB :grimacing: 

```
./node_modules/.bin/sls --version
Framework Core: 2.18.0 (local)
Plugin: 4.4.2
SDK: 2.3.2
Components: 3.4.6
```

Fragment of my serverless.yml (although there's not much to look there)

```
service: xxxxx

frameworkVersion: ^2.16.1

plugins:
  - serverless-dotenv-plugin

custom:
  cors:
    allowCredentials: false
    origin: '*'
    headers:
      - Authorization
      - Content-Type
      - X-Amz-Date
      - X-Api-Key
      - X-Amz-Security-Token
      - X-Amz-User-Agent

package:
  excludeDevDependencies: true
  exclude:
    - .vscode
    - docker
    - .git/**
```

Let me know if it's not an issue with the plugin so I can file another issue. Let me know if I can help with anything
